package br.com.visao;

import br.com.controle.AlunoController;
import br.com.modelo.Aluno;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TelaListaAlunos extends javax.swing.JFrame {

    private List<Aluno> alunos;

    public TelaListaAlunos() {
        initComponents();
        montarListaAlunos();
    }

    public void montarListaAlunos() {
        AlunoController alunoController = new AlunoController();
        alunos = alunoController.listarAlunos();

        DefaultTableModel modeloTabela = (DefaultTableModel) jTable1.getModel();
        modeloTabela.setRowCount(0);

        for (Aluno aluno : alunos) {
            Object[] linha = {
                aluno.getId(),
                aluno.getNome(),
                aluno.getGenero(),
                aluno.getEndereco(),
                aluno.getTelefone(),
                aluno.getEmail()
            };

            modeloTabela.addRow(linha);
        }
    }

    private javax.swing.JTable tabAlunos;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(121, 165, 95));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Gênero", "Endereço", "Telefone", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Deletar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de Alunos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)))
                        .addGap(0, 155, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int linha = jTable1.getSelectedRow();
        if (linha > -1) {
            Aluno aluno = alunos.get(linha);
            int opcao = JOptionPane.showConfirmDialog(this,
                    "Deseja realmente excluir o aluno " + aluno.getNome() + "?",
                    "Confirme a exclusão", JOptionPane.YES_NO_OPTION);

            if (opcao == JOptionPane.YES_OPTION) {
                AlunoController alunoController = new AlunoController();
                alunoController.excluirAluno(aluno.getId());
                JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!");
                montarListaAlunos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para excluir!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        atualizarAluno();
    }//GEN-LAST:event_jButton2ActionPerformed
    private void atualizarAluno() {
        int linha = jTable1.getSelectedRow();
        if (linha > -1) {
            Aluno aluno = alunos.get(linha);

            // Solicita novos valores ao usuário
            String novoNome = JOptionPane.showInputDialog(this, "Novo nome:", aluno.getNome());
            String novoGenero = JOptionPane.showInputDialog(this, "Novo gênero:", aluno.getGenero());
            String novoEndereco = JOptionPane.showInputDialog(this, "Novo endereço:", aluno.getEndereco());
            String novoTelefone = JOptionPane.showInputDialog(this, "Novo telefone:", aluno.getTelefone());
            String novoEmail = JOptionPane.showInputDialog(this, "Novo email:", aluno.getEmail());

            // Atualiza os dados do aluno
            aluno.setNome(novoNome);
            aluno.setGenero(novoGenero);
            aluno.setEndereco(novoEndereco);
            aluno.setTelefone(novoTelefone);
            aluno.setEmail(novoEmail);

            // Chama o método para atualizar no banco de dados
            AlunoController alunoController = new AlunoController();
            alunoController.atualizarAluno(aluno);

            JOptionPane.showMessageDialog(this, "Aluno atualizado com sucesso!");
            montarListaAlunos();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para editar!");
        }
    }

    private void excluirAluno() {
        int linha = jTable1.getSelectedRow();
        if (linha > -1) {
            Aluno aluno = alunos.get(linha);
            int opcao = JOptionPane.showConfirmDialog(this,
                    "Deseja realmente excluir o aluno " + aluno.getNome() + "?",
                    "Confirme a exclusão", JOptionPane.YES_NO_OPTION);

            if (opcao == JOptionPane.YES_OPTION) {
                AlunoController alunoController = new AlunoController();
                alunoController.excluirAluno(aluno.getId());
                JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso!");
                montarListaAlunos();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um aluno para excluir!");
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaAlunos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> {
            new TelaListaAlunos().setVisible(true);

        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
